version: "2"

services:
  btc-app:
    image: ahmad4/leads-image
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: leads-db
      DB_USER: appuser
      DB_PASSWORD: toor
    depends_on:
      - db



  leads-app:
    image: ahmad4/bitcoin-app
    command: uvicorn bitcoin:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: leads-db
      DB_USER: appuser
      DB_PASSWORD: toor
    depends_on:
      - db


  
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:



